export const MUSCLE_EXERCISES = {
  chest: { label: 'Chest', color: '#ff6b6b', exercises: ['Bench Press','Incline Bench Press','Decline Bench Press','Cable Fly','Dumbbell Fly','Push-Ups','Chest Dips'] },
  back: { label: 'Back', color: '#54a0ff', exercises: ['Pull-Ups','Barbell Rows','Seated Cable Rows','Lat Pulldown','Deadlifts','T-Bar Rows','Face Pulls'] },
  shoulders: { label: 'Shoulders', color: '#7b61ff', exercises: ['Overhead Press','Lateral Raises','Front Raises','Arnold Press','Rear Delt Fly','Upright Rows'] },
  biceps: { label: 'Biceps', color: '#00f5c4', exercises: ['Barbell Curl','Dumbbell Curl','Hammer Curl','Preacher Curl','Concentration Curl','Cable Curl'] },
  triceps: { label: 'Triceps', color: '#ff9f43', exercises: ['Tricep Pushdown','Skull Crushers','Overhead Extension','Close-Grip Bench','Tricep Dips','Kickbacks'] },
  abs: { label: 'Abs', color: '#00f5c4', exercises: ['Crunches','Leg Raises','Planks','Russian Twists','Cable Crunches','Hanging Knee Raises','Ab Rollouts'] },
  quads: { label: 'Quads', color: '#ff6b6b', exercises: ['Squats','Leg Press','Lunges','Leg Extensions','Bulgarian Split Squat','Hack Squat','Step-Ups'] },
  hamstrings: { label: 'Hamstrings', color: '#54a0ff', exercises: ['Romanian Deadlift','Leg Curl','Good Mornings','Glute-Ham Raises','Sumo Deadlift','Nordic Curl'] },
  glutes: { label: 'Glutes', color: '#7b61ff', exercises: ['Hip Thrust','Glute Bridge','Cable Kickbacks','Sumo Squat','Donkey Kicks','Step-Ups'] },
  calves: { label: 'Calves', color: '#ff9f43', exercises: ['Standing Calf Raise','Seated Calf Raise','Donkey Calf Raise','Jump Rope','Leg Press Calf Raise'] },
};

export const WORKOUT_TYPES = ['Push','Pull','Legs','Upper Body','Lower Body','Full Body','Cardio','HIIT','Mobility','Custom'];

export const QUOTES = [
  { text: 'Lock in. No excuses.', author: 'LockIn' },
  { text: 'The pain you feel today is the strength you feel tomorrow.', author: 'Real' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Halpert' },
  { text: "Don't limit your challenges. Challenge your limits.", author: 'Nga' },
  { text: 'The only bad workout is the one that did not happen.', author: 'Piyush' },
];

// Preset exercises per workout type with emoji icons
export const PRESET_EXERCISES = {
  Push: [
    { name: 'Bench Press',         emoji: '🏋️', muscle: 'Chest' },
    { name: 'Incline Bench Press', emoji: '📐', muscle: 'Upper Chest' },
    { name: 'Shoulder Press',      emoji: '💪', muscle: 'Shoulders' },
    { name: 'Lateral Raises',      emoji: '🦅', muscle: 'Side Delts' },
    { name: 'Tricep Pushdown',     emoji: '⬇️', muscle: 'Triceps' },
    { name: 'Skull Crushers',      emoji: '💀', muscle: 'Triceps' },
    { name: 'Cable Fly',           emoji: '🔀', muscle: 'Chest' },
    { name: 'Dips',                emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Push-Ups',            emoji: '⬆️', muscle: 'Chest' },
    { name: 'Front Raises',        emoji: '🙌', muscle: 'Front Delts' },
  ],
  Pull: [
    { name: 'Pull-Ups',            emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Barbell Rows',        emoji: '🚣', muscle: 'Back' },
    { name: 'Lat Pulldown',        emoji: '⬇️', muscle: 'Lats' },
    { name: 'Seated Cable Rows',   emoji: '🎣', muscle: 'Mid Back' },
    { name: 'Deadlifts',           emoji: '🏋️', muscle: 'Back/Glutes' },
    { name: 'Barbell Curl',        emoji: '💪', muscle: 'Biceps' },
    { name: 'Hammer Curl',         emoji: '🔨', muscle: 'Biceps' },
    { name: 'Face Pulls',          emoji: '😤', muscle: 'Rear Delts' },
    { name: 'T-Bar Rows',          emoji: '🏗️', muscle: 'Back' },
    { name: 'Preacher Curl',       emoji: '🙏', muscle: 'Biceps' },
  ],
  Legs: [
    { name: 'Squats',              emoji: '🏋️', muscle: 'Quads/Glutes' },
    { name: 'Leg Press',           emoji: '🦵', muscle: 'Quads' },
    { name: 'Romanian Deadlift',   emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Leg Extensions',      emoji: '⬆️', muscle: 'Quads' },
    { name: 'Leg Curl',            emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Hip Thrust',          emoji: '🍑', muscle: 'Glutes' },
    { name: 'Lunges',              emoji: '🚶', muscle: 'Quads/Glutes' },
    { name: 'Calf Raises',         emoji: '🦶', muscle: 'Calves' },
    { name: 'Bulgarian Split Squat', emoji: '🧗', muscle: 'Quads' },
    { name: 'Hack Squat',          emoji: '📐', muscle: 'Quads' },
  ],
  'Upper Body': [
    { name: 'Bench Press',         emoji: '🏋️', muscle: 'Chest' },
    { name: 'Shoulder Press',      emoji: '💪', muscle: 'Shoulders' },
    { name: 'Pull-Ups',            emoji: '🔝', muscle: 'Back' },
    { name: 'Barbell Rows',        emoji: '🚣', muscle: 'Back' },
    { name: 'Barbell Curl',        emoji: '💪', muscle: 'Biceps' },
    { name: 'Tricep Pushdown',     emoji: '⬇️', muscle: 'Triceps' },
    { name: 'Lateral Raises',      emoji: '🦅', muscle: 'Shoulders' },
    { name: 'Face Pulls',          emoji: '😤', muscle: 'Rear Delts' },
  ],
  'Lower Body': [
    { name: 'Squats',              emoji: '🏋️', muscle: 'Quads/Glutes' },
    { name: 'Romanian Deadlift',   emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Leg Press',           emoji: '🦵', muscle: 'Quads' },
    { name: 'Hip Thrust',          emoji: '🍑', muscle: 'Glutes' },
    { name: 'Leg Curl',            emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Calf Raises',         emoji: '🦶', muscle: 'Calves' },
    { name: 'Lunges',              emoji: '🚶', muscle: 'Quads/Glutes' },
  ],
  'Full Body': [
    { name: 'Deadlifts',           emoji: '🏋️', muscle: 'Full Body' },
    { name: 'Squats',              emoji: '🏗️', muscle: 'Quads/Glutes' },
    { name: 'Bench Press',         emoji: '💪', muscle: 'Chest' },
    { name: 'Pull-Ups',            emoji: '🔝', muscle: 'Back' },
    { name: 'Shoulder Press',      emoji: '🦅', muscle: 'Shoulders' },
    { name: 'Barbell Rows',        emoji: '🚣', muscle: 'Back' },
    { name: 'Dips',                emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Barbell Curl',        emoji: '🔄', muscle: 'Biceps' },
  ],
  Cardio: [
    { name: 'Treadmill Run',       emoji: '🏃', muscle: 'Cardio' },
    { name: 'Jump Rope',           emoji: '🪢', muscle: 'Cardio' },
    { name: 'Cycling',             emoji: '🚴', muscle: 'Cardio' },
    { name: 'Stair Climber',       emoji: '🪜', muscle: 'Cardio' },
    { name: 'Rowing Machine',      emoji: '🚣', muscle: 'Cardio' },
    { name: 'Elliptical',          emoji: '🔄', muscle: 'Cardio' },
  ],
  HIIT: [
    { name: 'Burpees',             emoji: '💥', muscle: 'Full Body' },
    { name: 'Box Jumps',           emoji: '📦', muscle: 'Legs' },
    { name: 'Mountain Climbers',   emoji: '🧗', muscle: 'Core' },
    { name: 'Jump Squats',         emoji: '⬆️', muscle: 'Legs' },
    { name: 'Kettlebell Swings',   emoji: '🔔', muscle: 'Full Body' },
    { name: 'Battle Ropes',        emoji: '🌊', muscle: 'Arms/Core' },
  ],
  Mobility: [
    { name: 'Hip Flexor Stretch',  emoji: '🧘', muscle: 'Hips' },
    { name: 'Shoulder Dislocates', emoji: '🔄', muscle: 'Shoulders' },
    { name: 'Cat-Cow',             emoji: '🐱', muscle: 'Spine' },
    { name: 'Pigeon Pose',         emoji: '🕊️', muscle: 'Hips/Glutes' },
    { name: 'Worlds Greatest Stretch', emoji: '🌍', muscle: 'Full Body' },
    { name: 'Thoracic Rotation',   emoji: '🌀', muscle: 'Upper Back' },
  ],
  Custom: [],
};
