export const MUSCLE_EXERCISES = {
  chest: { label: 'Chest', color: '#ff6b6b', exercises: ['Barbell Bench Press','Dumbbell Bench Press','Incline Barbell Bench Press','Incline Dumbbell Bench Press','Decline Barbell Bench Press','Decline Dumbbell Bench Press','Cable Fly','Low to High Cable Fly','High to Low Cable Fly','Cable Crossover','Dumbbell Fly','Incline Dumbbell Fly','Pec Deck','Push-Ups','Chest Dips','Dumbbell Pullover','Landmine Press','Svend Press','Floor Press','Planche Push-Up','Pike Push-Ups','Plyo Push-Ups'] },
  back: { label: 'Back', color: '#54a0ff', exercises: ['Pull-Ups','Chin-Ups','Barbell Row','Dumbbell Row','Seated Cable Row','Cable Row','Lat Pulldown','Barbell Deadlift','Conventional Deadlift','T-Bar Row','Face Pulls','Chest-Supported Dumbbell Row','Single-Arm Dumbbell Row','Meadows Row','Straight-Arm Pulldown','Rack Pull','Pendlay Row','Ring Rows','Front Lever','Dead Hang'] },
  shoulders: { label: 'Shoulders', color: '#7b61ff', exercises: ['Barbell Overhead Press','Dumbbell Shoulder Press','Arnold Press','Push Press','Bradford Press','Machine Shoulder Press','Dumbbell Lateral Raise','Cable Lateral Raise','Cable Face Pull','Barbell Upright Row','Dumbbell Front Raise','Plate Front Raise','Lu Raise','Rear Delt Dumbbell Fly','Handstand Push-Up','Wall Slides','Shoulder Dislocates'] },
  biceps: { label: 'Biceps', color: '#00f5c4', exercises: ['Barbell Curl','Dumbbell Curl','Hammer Curl','Incline Dumbbell Curl','Preacher Curl','Cable Curl','Concentration Curl','Spider Curl','Reverse Barbell Curl','Zottman Curl','21s','Cross-Body Hammer Curl','EZ Bar Curl'] },
  triceps: { label: 'Triceps', color: '#ff9f43', exercises: ['Cable Tricep Pushdown','Rope Pushdown','Barbell Skull Crushers','Dumbbell Overhead Tricep Extension','Close-Grip Bench Press','Tricep Dips','Diamond Push-Ups','Dumbbell Kickbacks','JM Press','Tate Press','Single-Arm Cable Pushdown','Cable Overhead Tricep Extension'] },
  abs: { label: 'Abs / Core', color: '#9867cd', exercises: ['Crunches','Leg Raises','Plank','Russian Twists','Cable Crunches','Hanging Knee Raises','Ab Rollout','Dead Bug','Dragon Flag','Hollow Body Hold','Pallof Press','L-Sit','Windshield Wipers','Toe Touches','Bicycle Crunches','Side Plank','V-Ups','Mountain Climbers'] },
  quads: { label: 'Quads', color: '#ff6b6b', exercises: ['Barbell Back Squat','Dumbbell Goblet Squat','Leg Press','Dumbbell Lunges','Barbell Lunges','Leg Extensions','Bulgarian Split Squat','Hack Squat','Step-Ups','Front Squat','Sissy Squat','Cyclist Squat','Spanish Squat','Wall Sit','Barbell Box Squat','Belt Squat','Pause Squat','Pistol Squat','Jump Squats','Jumping Lunges','Box Jumps'] },
  hamstrings: { label: 'Hamstrings', color: '#54a0ff', exercises: ['Romanian Deadlift','Barbell Romanian Deadlift','Dumbbell Romanian Deadlift','Leg Curl','Lying Leg Curl','Seated Leg Curl','Good Mornings','Glute-Ham Raise','Sumo Deadlift','Nordic Curl','Single-Leg RDL','Stiff-Leg Deadlift','Snatch-Grip Deadlift','Jefferson Curl'] },
  glutes: { label: 'Glutes', color: '#7b61ff', exercises: ['Barbell Hip Thrust','Dumbbell Hip Thrust','Glute Bridge','Single-Leg Hip Thrust','Cable Kickbacks','Sumo Squat','Donkey Kicks','Step-Ups','Clamshells','Abductor Machine','Romanian Deadlift','Frog Pump','Banded Walk'] },
  calves: { label: 'Calves', color: '#ff9f43', exercises: ['Standing Calf Raise','Seated Calf Raise','Donkey Calf Raise','Leg Press Calf Raise','Single-Leg Calf Raise','Tibialis Raise','Loaded Stretch Calf Raise','Box Jumps','Jump Rope'] },
  forearms: { label: 'Forearms', color: '#fd79a8', exercises: ['Wrist Curl','Reverse Wrist Curl','Farmers Carry','Dead Hang','Reverse Barbell Curl','Hammer Curl','Plate Pinch','Towel Pull-Up','Wrist Roller'] },
  traps: { label: 'Traps', color: '#fdcb6e', exercises: ['Barbell Shrugs','Dumbbell Shrugs','Face Pulls','Rack Pull','Farmers Carry','Power Clean','Snatch-Grip Deadlift','Cable Shrug'] },
};

export const WORKOUT_TYPES = ['Push','Pull','Legs','Upper Body','Lower Body','Full Body','Cardio','HIIT','Mobility','Powerlifting','Calisthenics','Custom'];

export const QUOTES = [
  { text: 'Lock in. No excuses.', author: 'LockIn' },
  { text: 'The pain you feel today is the strength you feel tomorrow.', author: 'Real' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Piyush' },
  { text: "Don't limit your challenges. Challenge your limits.", author: 'LockIn' },
  { text: 'The only bad workout is the one that did not happen.', author: 'Piyush' },
  { text: 'The body achieves what the mind believes.', author: 'LockIn' },
  { text: 'One more rep. Always one more.', author: 'Piyush' },
];

export const PRESET_EXERCISES = {
  Push: [
    // ── Chest ────────────────────────────────────────────────────────────
    { name: 'Barbell Bench Press',                emoji: '🏋️', muscle: 'Chest' },
    { name: 'Dumbbell Bench Press',               emoji: '🥊', muscle: 'Chest' },
    { name: 'Incline Barbell Bench Press',        emoji: '📐', muscle: 'Upper Chest' },
    { name: 'Incline Dumbbell Bench Press',       emoji: '📐', muscle: 'Upper Chest' },
    { name: 'Decline Barbell Bench Press',        emoji: '📉', muscle: 'Lower Chest' },
    { name: 'Decline Dumbbell Bench Press',       emoji: '📉', muscle: 'Lower Chest' },
    { name: 'Dumbbell Fly',                       emoji: '🦋', muscle: 'Chest' },
    { name: 'Incline Dumbbell Fly',               emoji: '🦋', muscle: 'Upper Chest' },
    { name: 'Low to High Cable Fly',              emoji: '🦋', muscle: 'Upper Chest' },
    { name: 'High to Low Cable Fly',              emoji: '🔀', muscle: 'Chest' },
    { name: 'Cable Fly',                          emoji: '✂️', muscle: 'Chest' },
    { name: 'Cable Crossover',                    emoji: '✂️', muscle: 'Chest' },
    { name: 'Pec Deck',                           emoji: '🦋', muscle: 'Chest' },
    { name: 'Push-Ups',                           emoji: '⬆️', muscle: 'Chest' },
    { name: 'Plyo Push-Ups',                      emoji: '💨', muscle: 'Chest' },
    { name: 'Chest Dips',                         emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Dumbbell Pullover',                  emoji: '🔄', muscle: 'Chest/Lats' },
    { name: 'Landmine Press',                     emoji: '🏗️', muscle: 'Chest/Shoulders' },
    { name: 'Svend Press',                        emoji: '🤲', muscle: 'Chest' },
    { name: 'Floor Press',                        emoji: '⬛', muscle: 'Chest/Triceps' },
    // ── Shoulders ────────────────────────────────────────────────────────
    { name: 'Barbell Overhead Press',             emoji: '🏋️', muscle: 'Shoulders' },
    { name: 'Dumbbell Shoulder Press',            emoji: '💪', muscle: 'Shoulders' },
    { name: 'Arnold Press',                       emoji: '🌀', muscle: 'Shoulders' },
    { name: 'Push Press',                         emoji: '⚡', muscle: 'Shoulders' },
    { name: 'Bradford Press',                     emoji: '🔁', muscle: 'Shoulders' },
    { name: 'Machine Shoulder Press',             emoji: '🤖', muscle: 'Shoulders' },
    { name: 'Dumbbell Lateral Raise',             emoji: '🦅', muscle: 'Side Delts' },
    { name: 'Cable Lateral Raise',                emoji: '🦅', muscle: 'Side Delts' },
    { name: 'Dumbbell Front Raise',               emoji: '🙌', muscle: 'Front Delts' },
    { name: 'Plate Front Raise',                  emoji: '🥏', muscle: 'Front Delts' },
    { name: 'Lu Raise',                           emoji: '🌊', muscle: 'Side Delts' },
    { name: 'Barbell Upright Row',                emoji: '📏', muscle: 'Shoulders/Traps' },
    // ── Triceps ──────────────────────────────────────────────────────────
    { name: 'Cable Tricep Pushdown',              emoji: '⬇️', muscle: 'Triceps' },
    { name: 'Rope Pushdown',                      emoji: '🪢', muscle: 'Triceps' },
    { name: 'Barbell Skull Crushers',             emoji: '💀', muscle: 'Triceps' },
    { name: 'Dumbbell Overhead Tricep Extension', emoji: '🔼', muscle: 'Triceps' },
    { name: 'Cable Overhead Tricep Extension',    emoji: '🔼', muscle: 'Triceps' },
    { name: 'Single-Arm Cable Pushdown',          emoji: '1️⃣', muscle: 'Triceps' },
    { name: 'Close-Grip Bench Press',             emoji: '🤜', muscle: 'Triceps' },
    { name: 'Diamond Push-Ups',                   emoji: '💎', muscle: 'Triceps' },
    { name: 'Dumbbell Kickbacks',                 emoji: '🦵', muscle: 'Triceps' },
    { name: 'JM Press',                           emoji: '🔧', muscle: 'Triceps' },
    { name: 'Tate Press',                         emoji: '🏗️', muscle: 'Triceps' },
  ],

  Pull: [
    // ── Back ─────────────────────────────────────────────────────────────
    { name: 'Pull-Ups',                           emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Chin-Ups',                           emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Barbell Row',                        emoji: '🚣', muscle: 'Back' },
    { name: 'Dumbbell Row',                       emoji: '🚣', muscle: 'Back' },
    { name: 'Single-Arm Dumbbell Row',            emoji: '1️⃣', muscle: 'Back' },
    { name: 'Chest-Supported Dumbbell Row',       emoji: '🪑', muscle: 'Back' },
    { name: 'Seated Cable Row',                   emoji: '🎣', muscle: 'Mid Back' },
    { name: 'Cable Row',                          emoji: '🎣', muscle: 'Mid Back' },
    { name: 'Lat Pulldown',                       emoji: '⬇️', muscle: 'Lats' },
    { name: 'Straight-Arm Pulldown',              emoji: '📏', muscle: 'Lats' },
    { name: 'T-Bar Row',                          emoji: '🏗️', muscle: 'Back' },
    { name: 'Barbell Deadlift',                   emoji: '🏋️', muscle: 'Back/Glutes' },
    { name: 'Meadows Row',                        emoji: '🌾', muscle: 'Back' },
    { name: 'Pendlay Row',                        emoji: '🚣', muscle: 'Back' },
    { name: 'Rack Pull',                          emoji: '🔧', muscle: 'Back' },
    { name: 'Ring Rows',                          emoji: '💍', muscle: 'Back' },
    { name: 'Dead Hang',                          emoji: '🔔', muscle: 'Back/Forearms' },
    { name: 'Face Pulls',                         emoji: '😤', muscle: 'Rear Delts' },
    { name: 'Rear Delt Dumbbell Fly',             emoji: '🦅', muscle: 'Rear Delts' },
    { name: 'Cable Face Pull',                    emoji: '😤', muscle: 'Rear Delts' },
    // ── Biceps ───────────────────────────────────────────────────────────
    { name: 'Barbell Curl',                       emoji: '💪', muscle: 'Biceps' },
    { name: 'Dumbbell Curl',                      emoji: '💪', muscle: 'Biceps' },
    { name: 'Hammer Curl',                        emoji: '🔨', muscle: 'Biceps' },
    { name: 'Incline Dumbbell Curl',              emoji: '📐', muscle: 'Biceps' },
    { name: 'Preacher Curl',                      emoji: '🙏', muscle: 'Biceps' },
    { name: 'Cable Curl',                         emoji: '🔄', muscle: 'Biceps' },
    { name: 'Concentration Curl',                 emoji: '🎯', muscle: 'Biceps' },
    { name: 'EZ Bar Curl',                        emoji: '〰️', muscle: 'Biceps' },
    { name: 'Zottman Curl',                       emoji: '🌀', muscle: 'Biceps' },
    { name: 'Spider Curl',                        emoji: '🕷️', muscle: 'Biceps' },
    { name: '21s',                                emoji: '💥', muscle: 'Biceps' },
    { name: 'Cross-Body Hammer Curl',             emoji: '🔨', muscle: 'Biceps' },
    { name: 'Reverse Barbell Curl',               emoji: '🔃', muscle: 'Biceps/Forearms' },
    // ── Forearms ─────────────────────────────────────────────────────────
    { name: 'Wrist Curl',                         emoji: '🤲', muscle: 'Forearms' },
    { name: 'Reverse Wrist Curl',                 emoji: '🤲', muscle: 'Forearms' },
    { name: 'Farmers Carry',                      emoji: '🧺', muscle: 'Forearms/Traps' },
    { name: 'Plate Pinch',                        emoji: '🥏', muscle: 'Forearms' },
    { name: 'Towel Pull-Up',                      emoji: '🧻', muscle: 'Forearms/Back' },
    { name: 'Wrist Roller',                       emoji: '🎯', muscle: 'Forearms' },
    // ── Traps ─────────────────────────────────────────────────────────────
    { name: 'Barbell Shrugs',                     emoji: '🤷', muscle: 'Traps' },
    { name: 'Dumbbell Shrugs',                    emoji: '🤷', muscle: 'Traps' },
    { name: 'Cable Shrug',                        emoji: '🤷', muscle: 'Traps' },
    { name: 'Power Clean',                        emoji: '⚡', muscle: 'Traps/Full Body' },
  ],

  Legs: [
    // ── Quads ────────────────────────────────────────────────────────────
    { name: 'Barbell Back Squat',                 emoji: '🏋️', muscle: 'Quads/Glutes' },
    { name: 'Dumbbell Goblet Squat',              emoji: '🏆', muscle: 'Quads' },
    { name: 'Leg Press',                          emoji: '🦵', muscle: 'Quads' },
    { name: 'Leg Extensions',                     emoji: '⬆️', muscle: 'Quads' },
    { name: 'Bulgarian Split Squat',              emoji: '🧗', muscle: 'Quads' },
    { name: 'Hack Squat',                         emoji: '📐', muscle: 'Quads' },
    { name: 'Front Squat',                        emoji: '🔱', muscle: 'Quads' },
    { name: 'Barbell Lunges',                     emoji: '🚶', muscle: 'Quads/Glutes' },
    { name: 'Dumbbell Lunges',                    emoji: '🚶', muscle: 'Quads/Glutes' },
    { name: 'Sissy Squat',                        emoji: '🦵', muscle: 'Quads' },
    { name: 'Belt Squat',                         emoji: '🎽', muscle: 'Quads' },
    { name: 'Pause Squat',                        emoji: '⏸️', muscle: 'Quads' },
    { name: 'Barbell Box Squat',                  emoji: '📦', muscle: 'Quads/Glutes' },
    { name: 'Cyclist Squat',                      emoji: '🚴', muscle: 'Quads' },
    { name: 'Spanish Squat',                      emoji: '💺', muscle: 'Quads' },
    { name: 'Wall Sit',                           emoji: '🧱', muscle: 'Quads' },
    { name: 'Step-Ups',                           emoji: '🪜', muscle: 'Quads/Glutes' },
    // ── Hamstrings ───────────────────────────────────────────────────────
    { name: 'Barbell Romanian Deadlift',          emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Dumbbell Romanian Deadlift',         emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Romanian Deadlift',                  emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Lying Leg Curl',                     emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Seated Leg Curl',                    emoji: '🪑', muscle: 'Hamstrings' },
    { name: 'Leg Curl',                           emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Nordic Curl',                        emoji: '🛷', muscle: 'Hamstrings' },
    { name: 'Single-Leg RDL',                     emoji: '🦩', muscle: 'Hamstrings' },
    { name: 'Stiff-Leg Deadlift',                 emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Good Mornings',                      emoji: '🌅', muscle: 'Hamstrings/Back' },
    { name: 'Glute-Ham Raise',                    emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Snatch-Grip Deadlift',               emoji: '🏋️', muscle: 'Hamstrings/Back' },
    { name: 'Jefferson Curl',                     emoji: '🌿', muscle: 'Hamstrings/Spine' },
    // ── Glutes ───────────────────────────────────────────────────────────
    { name: 'Barbell Hip Thrust',                 emoji: '🍑', muscle: 'Glutes' },
    { name: 'Dumbbell Hip Thrust',                emoji: '🍑', muscle: 'Glutes' },
    { name: 'Glute Bridge',                       emoji: '🌉', muscle: 'Glutes' },
    { name: 'Single-Leg Hip Thrust',              emoji: '🍑', muscle: 'Glutes' },
    { name: 'Cable Kickbacks',                    emoji: '🦵', muscle: 'Glutes' },
    { name: 'Donkey Kicks',                       emoji: '🦵', muscle: 'Glutes' },
    { name: 'Clamshells',                         emoji: '🐚', muscle: 'Glutes' },
    { name: 'Abductor Machine',                   emoji: '🦿', muscle: 'Glutes' },
    { name: 'Frog Pump',                          emoji: '🐸', muscle: 'Glutes' },
    { name: 'Banded Walk',                        emoji: '🚶', muscle: 'Glutes' },
    { name: 'Sumo Squat',                         emoji: '🏋️', muscle: 'Glutes/Quads' },
    // ── Calves ───────────────────────────────────────────────────────────
    { name: 'Standing Calf Raise',                emoji: '🦶', muscle: 'Calves' },
    { name: 'Seated Calf Raise',                  emoji: '🦶', muscle: 'Calves' },
    { name: 'Donkey Calf Raise',                  emoji: '🦶', muscle: 'Calves' },
    { name: 'Leg Press Calf Raise',               emoji: '🦶', muscle: 'Calves' },
    { name: 'Single-Leg Calf Raise',              emoji: '🦶', muscle: 'Calves' },
    { name: 'Tibialis Raise',                     emoji: '🦵', muscle: 'Calves' },
    { name: 'Loaded Stretch Calf Raise',          emoji: '🦶', muscle: 'Calves' },
  ],

  'Upper Body': [
    { name: 'Barbell Bench Press',                emoji: '🏋️', muscle: 'Chest' },
    { name: 'Dumbbell Bench Press',               emoji: '🥊', muscle: 'Chest' },
    { name: 'Incline Dumbbell Bench Press',       emoji: '📐', muscle: 'Upper Chest' },
    { name: 'Barbell Overhead Press',             emoji: '🏋️', muscle: 'Shoulders' },
    { name: 'Dumbbell Shoulder Press',            emoji: '💪', muscle: 'Shoulders' },
    { name: 'Arnold Press',                       emoji: '🌀', muscle: 'Shoulders' },
    { name: 'Pull-Ups',                           emoji: '🔝', muscle: 'Back' },
    { name: 'Chin-Ups',                           emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Barbell Row',                        emoji: '🚣', muscle: 'Back' },
    { name: 'Dumbbell Row',                       emoji: '🚣', muscle: 'Back' },
    { name: 'Lat Pulldown',                       emoji: '⬇️', muscle: 'Lats' },
    { name: 'Seated Cable Row',                   emoji: '🎣', muscle: 'Mid Back' },
    { name: 'Barbell Curl',                       emoji: '💪', muscle: 'Biceps' },
    { name: 'Dumbbell Curl',                      emoji: '💪', muscle: 'Biceps' },
    { name: 'Hammer Curl',                        emoji: '🔨', muscle: 'Biceps' },
    { name: 'EZ Bar Curl',                        emoji: '〰️', muscle: 'Biceps' },
    { name: 'Cable Tricep Pushdown',              emoji: '⬇️', muscle: 'Triceps' },
    { name: 'Barbell Skull Crushers',             emoji: '💀', muscle: 'Triceps' },
    { name: 'Dumbbell Overhead Tricep Extension', emoji: '🔼', muscle: 'Triceps' },
    { name: 'Dumbbell Lateral Raise',             emoji: '🦅', muscle: 'Side Delts' },
    { name: 'Cable Lateral Raise',                emoji: '🦅', muscle: 'Side Delts' },
    { name: 'Face Pulls',                         emoji: '😤', muscle: 'Rear Delts' },
  ],

  'Lower Body': [
    { name: 'Barbell Back Squat',                 emoji: '🏋️', muscle: 'Quads/Glutes' },
    { name: 'Dumbbell Goblet Squat',              emoji: '🏆', muscle: 'Quads' },
    { name: 'Barbell Romanian Deadlift',          emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Dumbbell Romanian Deadlift',         emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Leg Press',                          emoji: '🦵', muscle: 'Quads' },
    { name: 'Barbell Hip Thrust',                 emoji: '🍑', muscle: 'Glutes' },
    { name: 'Dumbbell Hip Thrust',                emoji: '🍑', muscle: 'Glutes' },
    { name: 'Lying Leg Curl',                     emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Seated Leg Curl',                    emoji: '🪑', muscle: 'Hamstrings' },
    { name: 'Bulgarian Split Squat',              emoji: '🧗', muscle: 'Quads' },
    { name: 'Dumbbell Lunges',                    emoji: '🚶', muscle: 'Quads/Glutes' },
    { name: 'Glute Bridge',                       emoji: '🌉', muscle: 'Glutes' },
    { name: 'Nordic Curl',                        emoji: '🛷', muscle: 'Hamstrings' },
    { name: 'Single-Leg RDL',                     emoji: '🦩', muscle: 'Hamstrings' },
    { name: 'Standing Calf Raise',                emoji: '🦶', muscle: 'Calves' },
    { name: 'Seated Calf Raise',                  emoji: '🦶', muscle: 'Calves' },
    { name: 'Step-Ups',                           emoji: '🪜', muscle: 'Quads/Glutes' },
    { name: 'Cable Kickbacks',                    emoji: '🦵', muscle: 'Glutes' },
    { name: 'Abductor Machine',                   emoji: '🦿', muscle: 'Glutes' },
    { name: 'Leg Extensions',                     emoji: '⬆️', muscle: 'Quads' },
  ],

  'Full Body': [
    { name: 'Barbell Deadlift',                   emoji: '🏋️', muscle: 'Full Body' },
    { name: 'Conventional Deadlift',              emoji: '🏋️', muscle: 'Full Body' },
    { name: 'Barbell Back Squat',                 emoji: '🏗️', muscle: 'Quads/Glutes' },
    { name: 'Barbell Bench Press',                emoji: '💪', muscle: 'Chest' },
    { name: 'Barbell Overhead Press',             emoji: '🏋️', muscle: 'Shoulders' },
    { name: 'Pull-Ups',                           emoji: '🔝', muscle: 'Back' },
    { name: 'Barbell Row',                        emoji: '🚣', muscle: 'Back' },
    { name: 'Dumbbell Bench Press',               emoji: '🥊', muscle: 'Chest' },
    { name: 'Dumbbell Shoulder Press',            emoji: '💪', muscle: 'Shoulders' },
    { name: 'Chest Dips',                         emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Barbell Curl',                       emoji: '🔄', muscle: 'Biceps' },
    { name: 'Power Clean',                        emoji: '⚡', muscle: 'Full Body' },
    { name: 'Kettlebell Swings',                  emoji: '🔔', muscle: 'Full Body' },
    { name: 'Turkish Get-Up',                     emoji: '🌅', muscle: 'Full Body' },
    { name: 'Farmers Carry',                      emoji: '🧺', muscle: 'Full Body' },
    { name: 'Sled Push',                          emoji: '🛷', muscle: 'Full Body' },
    { name: 'Battle Ropes',                       emoji: '🌊', muscle: 'Full Body' },
  ],

  Cardio: [
    { name: 'Treadmill Run',                      emoji: '🏃', muscle: 'Cardio' },
    { name: 'Jump Rope',                          emoji: '🪢', muscle: 'Cardio' },
    { name: 'Cycling',                            emoji: '🚴', muscle: 'Cardio' },
    { name: 'Stair Climber',                      emoji: '🪜', muscle: 'Cardio' },
    { name: 'Rowing Machine',                     emoji: '🚣', muscle: 'Cardio' },
    { name: 'Elliptical',                         emoji: '🔄', muscle: 'Cardio' },
    { name: 'Sprint Intervals',                   emoji: '⚡', muscle: 'Cardio' },
    { name: 'Swimming',                           emoji: '🏊', muscle: 'Cardio' },
    { name: 'Assault Bike',                       emoji: '💨', muscle: 'Cardio' },
    { name: 'Incline Walk',                       emoji: '⛰️', muscle: 'Cardio' },
  ],

  HIIT: [
    { name: 'Burpees',                            emoji: '💥', muscle: 'Full Body' },
    { name: 'Box Jumps',                          emoji: '📦', muscle: 'Legs' },
    { name: 'Mountain Climbers',                  emoji: '🧗', muscle: 'Core' },
    { name: 'Jump Squats',                        emoji: '⬆️', muscle: 'Legs' },
    { name: 'Kettlebell Swings',                  emoji: '🔔', muscle: 'Full Body' },
    { name: 'Battle Ropes',                       emoji: '🌊', muscle: 'Arms/Core' },
    { name: 'Jumping Lunges',                     emoji: '🦘', muscle: 'Legs' },
    { name: 'High Knees',                         emoji: '🦵', muscle: 'Cardio' },
    { name: 'Plyo Push-Ups',                      emoji: '💨', muscle: 'Chest' },
    { name: 'Tuck Jumps',                         emoji: '🐸', muscle: 'Legs' },
    { name: 'Assault Bike Sprint',                emoji: '🚴', muscle: 'Cardio' },
    { name: 'Sled Push',                          emoji: '🛷', muscle: 'Full Body' },
    // ── Core ─────────────────────────────────────────────────────────────
    { name: 'Crunches',                           emoji: '🔄', muscle: 'Core' },
    { name: 'Bicycle Crunches',                   emoji: '🚴', muscle: 'Core' },
    { name: 'Leg Raises',                         emoji: '🦵', muscle: 'Core' },
    { name: 'Plank',                              emoji: '🧱', muscle: 'Core' },
    { name: 'Side Plank',                         emoji: '🧱', muscle: 'Core' },
    { name: 'Russian Twists',                     emoji: '🌀', muscle: 'Core' },
    { name: 'Cable Crunches',                     emoji: '🎣', muscle: 'Core' },
    { name: 'Dead Bug',                           emoji: '🐛', muscle: 'Core' },
    { name: 'Pallof Press',                       emoji: '🎯', muscle: 'Core' },
    { name: 'V-Ups',                              emoji: '✌️', muscle: 'Core' },
    { name: 'Toe Touches',                        emoji: '🦶', muscle: 'Core' },
    { name: 'Windshield Wipers',                  emoji: '🌀', muscle: 'Core' },
  ],

  Mobility: [
    { name: 'Hip Flexor Stretch',                 emoji: '🧘', muscle: 'Hips' },
    { name: 'Shoulder Dislocates',                emoji: '🔄', muscle: 'Shoulders' },
    { name: 'Cat-Cow',                            emoji: '🐱', muscle: 'Spine' },
    { name: 'Pigeon Pose',                        emoji: '🕊️', muscle: 'Hips/Glutes' },
    { name: 'Worlds Greatest Stretch',            emoji: '🌍', muscle: 'Full Body' },
    { name: 'Thoracic Rotation',                  emoji: '🌀', muscle: 'Upper Back' },
    { name: 'Deep Squat Hold',                    emoji: '🏋️', muscle: 'Hips/Ankles' },
    { name: 'Couch Stretch',                      emoji: '🛋️', muscle: 'Hip Flexors' },
    { name: 'Downward Dog',                       emoji: '🐕', muscle: 'Full Body' },
    { name: '90/90 Hip Switch',                   emoji: '🔁', muscle: 'Hips' },
    { name: 'Wall Slides',                        emoji: '🧱', muscle: 'Shoulders' },
    { name: 'Jefferson Curl',                     emoji: '🌿', muscle: 'Spine/Hamstrings' },
  ],

  Powerlifting: [
    { name: 'Barbell Back Squat',                 emoji: '🏆', muscle: 'Quads/Glutes' },
    { name: 'Conventional Deadlift',              emoji: '🏋️', muscle: 'Full Body' },
    { name: 'Barbell Bench Press',                emoji: '💪', muscle: 'Chest' },
    { name: 'Sumo Deadlift',                      emoji: '🔱', muscle: 'Glutes/Back' },
    { name: 'Close-Grip Bench Press',             emoji: '🤜', muscle: 'Triceps' },
    { name: 'Pause Squat',                        emoji: '⏸️', muscle: 'Quads' },
    { name: 'Rack Pull',                          emoji: '🔧', muscle: 'Back' },
    { name: 'Barbell Romanian Deadlift',          emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Barbell Box Squat',                  emoji: '📦', muscle: 'Quads/Glutes' },
    { name: 'Floor Press',                        emoji: '⬛', muscle: 'Chest/Triceps' },
    { name: 'Good Mornings',                      emoji: '🌅', muscle: 'Hamstrings/Back' },
    { name: 'Belt Squat',                         emoji: '🎽', muscle: 'Quads' },
    { name: 'Snatch-Grip Deadlift',               emoji: '🏋️', muscle: 'Hamstrings/Back' },
    { name: 'Barbell Overhead Press',             emoji: '🏋️', muscle: 'Shoulders' },
    { name: 'Barbell Row',                        emoji: '🚣', muscle: 'Back' },
  ],

  Calisthenics: [
    { name: 'Pull-Ups',                           emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Chin-Ups',                           emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Ring Rows',                          emoji: '💍', muscle: 'Back' },
    { name: 'Front Lever',                        emoji: '📐', muscle: 'Back/Core' },
    { name: 'Tricep Dips',                        emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Push-Ups',                           emoji: '⬆️', muscle: 'Chest' },
    { name: 'Diamond Push-Ups',                   emoji: '💎', muscle: 'Triceps' },
    { name: 'Pike Push-Ups',                      emoji: '🔺', muscle: 'Shoulders' },
    { name: 'Plyo Push-Ups',                      emoji: '💨', muscle: 'Chest' },
    { name: 'Handstand Push-Up',                  emoji: '🙃', muscle: 'Shoulders' },
    { name: 'Planche Push-Up',                    emoji: '✈️', muscle: 'Chest/Shoulders' },
    { name: 'Muscle-Up',                          emoji: '⭐', muscle: 'Full Body' },
    { name: 'Human Flag',                         emoji: '🚩', muscle: 'Full Body' },
    { name: 'Pistol Squat',                       emoji: '🦯', muscle: 'Quads' },
    { name: 'L-Sit',                              emoji: '💺', muscle: 'Core' },
    { name: 'Dragon Flag',                        emoji: '🐉', muscle: 'Core' },
    { name: 'Hollow Body Hold',                   emoji: '🫙', muscle: 'Core' },
    { name: 'Ab Rollout',                         emoji: '🎯', muscle: 'Core' },
    { name: 'Hanging Knee Raises',                emoji: '🦵', muscle: 'Core' },
    { name: 'Dead Hang',                          emoji: '🔔', muscle: 'Back/Forearms' },
  ],

  Custom: [],
};
