export const MUSCLE_EXERCISES = {
  chest: { label: 'Chest', color: '#ff6b6b', exercises: ['Bench Press','Incline Bench Press','Decline Bench Press','Cable Fly','Dumbbell Fly','Push-Ups','Chest Dips','Pec Deck','Landmine Press','Svend Press','Low Cable Fly','High Cable Fly'] },
  back: { label: 'Back', color: '#54a0ff', exercises: ['Pull-Ups','Barbell Rows','Seated Cable Rows','Lat Pulldown','Deadlifts','T-Bar Rows','Face Pulls','Chest-Supported Row','Single-Arm Dumbbell Row','Meadows Row','Straight-Arm Pulldown','Rack Pull','Pendlay Row'] },
  shoulders: { label: 'Shoulders', color: '#7b61ff', exercises: ['Overhead Press','Lateral Raises','Front Raises','Arnold Press','Rear Delt Fly','Upright Rows','Cable Lateral Raise','Machine Shoulder Press','Push Press','Bradford Press','Plate Front Raise','Lu Raise'] },
  biceps: { label: 'Biceps', color: '#00f5c4', exercises: ['Barbell Curl','Dumbbell Curl','Hammer Curl','Preacher Curl','Concentration Curl','Cable Curl','Incline Dumbbell Curl','Spider Curl','Reverse Curl','Zottman Curl','21s','Cross-Body Hammer Curl'] },
  triceps: { label: 'Triceps', color: '#ff9f43', exercises: ['Tricep Pushdown','Skull Crushers','Overhead Extension','Close-Grip Bench','Tricep Dips','Kickbacks','JM Press','Tate Press','Single-Arm Overhead Extension','Cable Overhead Extension','Diamond Push-Ups'] },
  abs: { label: 'Abs', color: '#9867cd', exercises: ['Crunches','Leg Raises','Planks','Russian Twists','Cable Crunches','Hanging Knee Raises','Ab Rollouts','Dead Bug','Dragon Flag','Hollow Body Hold','Pallof Press','L-Sit','Windshield Wipers','Toe Touches'] },
  quads: { label: 'Quads', color: '#ff6b6b', exercises: ['Squats','Leg Press','Lunges','Leg Extensions','Bulgarian Split Squat','Hack Squat','Step-Ups','Front Squat','Goblet Squat','Sissy Squat','Cyclist Squat','Spanish Squat','Wall Sit'] },
  hamstrings: { label: 'Hamstrings', color: '#54a0ff', exercises: ['Romanian Deadlift','Leg Curl','Good Mornings','Glute-Ham Raises','Sumo Deadlift','Nordic Curl','Single-Leg RDL','Lying Leg Curl','Seated Leg Curl','Stiff-Leg Deadlift','Snatch-Grip Deadlift'] },
  glutes: { label: 'Glutes', color: '#7b61ff', exercises: ['Hip Thrust','Glute Bridge','Cable Kickbacks','Sumo Squat','Donkey Kicks','Step-Ups','Single-Leg Hip Thrust','Clamshells','Abductor Machine','Banded Walk','Romanian Deadlift','Frog Pump'] },
  calves: { label: 'Calves', color: '#ff9f43', exercises: ['Standing Calf Raise','Seated Calf Raise','Donkey Calf Raise','Jump Rope','Leg Press Calf Raise','Single-Leg Calf Raise','Tibialis Raise','Box Jump','Loaded Stretch Calf Raise'] },
  forearms: { label: 'Forearms', color: '#fd79a8', exercises: ['Wrist Curl','Reverse Wrist Curl','Farmers Carry','Dead Hang','Reverse Curl','Hammer Curl','Plate Pinch','Towel Pull-Up','Wrist Roller'] },
  traps: { label: 'Traps', color: '#fdcb6e', exercises: ['Shrugs','Barbell Shrugs','Dumbbell Shrugs','Face Pulls','Rack Pull','Farmer Carry','Power Clean','Snatch Grip Deadlift','Cable Shrug'] },
};

export const WORKOUT_TYPES = ['Push','Pull','Legs','Upper Body','Lower Body','Full Body','Cardio','HIIT','Mobility','Powerlifting','Calisthenics','Custom'];

export const QUOTES = [
  { text: 'Lock in. No excuses.', author: 'LockIn' },
  { text: 'The pain you feel today is the strength you feel tomorrow.', author: 'Real' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Halpert' },
  { text: "Don't limit your challenges. Challenge your limits.", author: 'Nga' },
  { text: 'The only bad workout is the one that did not happen.', author: 'Piyush' },
  { text: 'Fall in love with the process and the results will come.', author: 'LockIn' },
  { text: 'You do not rise to the level of your goals, you fall to the level of your systems.', author: 'James Clear' },
  { text: 'Strength does not come from what you can do. It comes from overcoming what you thought you could not.', author: 'Rikki Rogers' },
  { text: 'The body achieves what the mind believes.', author: 'LockIn' },
  { text: 'One more rep. Always one more.', author: 'LockIn' },
];

export const PRESET_EXERCISES = {
  Push: [
    { name: 'Bench Press',           emoji: '🏋️', muscle: 'Chest' },
    { name: 'Incline Bench Press',   emoji: '📐', muscle: 'Upper Chest' },
    { name: 'Decline Bench Press',   emoji: '📉', muscle: 'Lower Chest' },
    { name: 'Shoulder Press',        emoji: '💪', muscle: 'Shoulders' },
    { name: 'Arnold Press',          emoji: '🌀', muscle: 'Shoulders' },
    { name: 'Lateral Raises',        emoji: '🦅', muscle: 'Side Delts' },
    { name: 'Tricep Pushdown',       emoji: '⬇️', muscle: 'Triceps' },
    { name: 'Skull Crushers',        emoji: '💀', muscle: 'Triceps' },
    { name: 'Cable Fly',             emoji: '🔀', muscle: 'Chest' },
    { name: 'Dips',                  emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Push-Ups',              emoji: '⬆️', muscle: 'Chest' },
    { name: 'Front Raises',          emoji: '🙌', muscle: 'Front Delts' },
    { name: 'Pec Deck',              emoji: '🦋', muscle: 'Chest' },
    { name: 'Overhead Extension',    emoji: '🔼', muscle: 'Triceps' },
    { name: 'Close-Grip Bench',      emoji: '🤜', muscle: 'Triceps' },
  ],
  Pull: [
    { name: 'Pull-Ups',              emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Barbell Rows',          emoji: '🚣', muscle: 'Back' },
    { name: 'Lat Pulldown',          emoji: '⬇️', muscle: 'Lats' },
    { name: 'Seated Cable Rows',     emoji: '🎣', muscle: 'Mid Back' },
    { name: 'Deadlifts',             emoji: '🏋️', muscle: 'Back/Glutes' },
    { name: 'Barbell Curl',          emoji: '💪', muscle: 'Biceps' },
    { name: 'Hammer Curl',           emoji: '🔨', muscle: 'Biceps' },
    { name: 'Face Pulls',            emoji: '😤', muscle: 'Rear Delts' },
    { name: 'T-Bar Rows',            emoji: '🏗️', muscle: 'Back' },
    { name: 'Preacher Curl',         emoji: '🙏', muscle: 'Biceps' },
    { name: 'Single-Arm DB Row',     emoji: '1️⃣', muscle: 'Back' },
    { name: 'Straight-Arm Pulldown', emoji: '📏', muscle: 'Lats' },
    { name: 'Incline Dumbbell Curl', emoji: '📐', muscle: 'Biceps' },
    { name: 'Chest-Supported Row',   emoji: '🪑', muscle: 'Back' },
    { name: 'Meadows Row',           emoji: '🌾', muscle: 'Back' },
  ],
  Legs: [
    { name: 'Squats',                emoji: '🏋️', muscle: 'Quads/Glutes' },
    { name: 'Leg Press',             emoji: '🦵', muscle: 'Quads' },
    { name: 'Romanian Deadlift',     emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Leg Extensions',        emoji: '⬆️', muscle: 'Quads' },
    { name: 'Leg Curl',              emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Hip Thrust',            emoji: '🍑', muscle: 'Glutes' },
    { name: 'Lunges',                emoji: '🚶', muscle: 'Quads/Glutes' },
    { name: 'Calf Raises',           emoji: '🦶', muscle: 'Calves' },
    { name: 'Bulgarian Split Squat', emoji: '🧗', muscle: 'Quads' },
    { name: 'Hack Squat',            emoji: '📐', muscle: 'Quads' },
    { name: 'Front Squat',           emoji: '🔱', muscle: 'Quads' },
    { name: 'Goblet Squat',          emoji: '🏆', muscle: 'Quads' },
    { name: 'Nordic Curl',           emoji: '🛷', muscle: 'Hamstrings' },
    { name: 'Single-Leg RDL',        emoji: '🦩', muscle: 'Hamstrings' },
    { name: 'Glute Bridge',          emoji: '🌉', muscle: 'Glutes' },
  ],
  'Upper Body': [
    { name: 'Bench Press',           emoji: '🏋️', muscle: 'Chest' },
    { name: 'Shoulder Press',        emoji: '💪', muscle: 'Shoulders' },
    { name: 'Pull-Ups',              emoji: '🔝', muscle: 'Back' },
    { name: 'Barbell Rows',          emoji: '🚣', muscle: 'Back' },
    { name: 'Barbell Curl',          emoji: '💪', muscle: 'Biceps' },
    { name: 'Tricep Pushdown',       emoji: '⬇️', muscle: 'Triceps' },
    { name: 'Lateral Raises',        emoji: '🦅', muscle: 'Shoulders' },
    { name: 'Face Pulls',            emoji: '😤', muscle: 'Rear Delts' },
    { name: 'Incline Bench Press',   emoji: '📐', muscle: 'Upper Chest' },
    { name: 'Lat Pulldown',          emoji: '⬇️', muscle: 'Lats' },
    { name: 'Arnold Press',          emoji: '🌀', muscle: 'Shoulders' },
    { name: 'Skull Crushers',        emoji: '💀', muscle: 'Triceps' },
  ],
  'Lower Body': [
    { name: 'Squats',                emoji: '🏋️', muscle: 'Quads/Glutes' },
    { name: 'Romanian Deadlift',     emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Leg Press',             emoji: '🦵', muscle: 'Quads' },
    { name: 'Hip Thrust',            emoji: '🍑', muscle: 'Glutes' },
    { name: 'Leg Curl',              emoji: '🔄', muscle: 'Hamstrings' },
    { name: 'Calf Raises',           emoji: '🦶', muscle: 'Calves' },
    { name: 'Lunges',                emoji: '🚶', muscle: 'Quads/Glutes' },
    { name: 'Bulgarian Split Squat', emoji: '🧗', muscle: 'Quads' },
    { name: 'Glute Bridge',          emoji: '🌉', muscle: 'Glutes' },
    { name: 'Nordic Curl',           emoji: '🛷', muscle: 'Hamstrings' },
  ],
  'Full Body': [
    { name: 'Deadlifts',             emoji: '🏋️', muscle: 'Full Body' },
    { name: 'Squats',                emoji: '🏗️', muscle: 'Quads/Glutes' },
    { name: 'Bench Press',           emoji: '💪', muscle: 'Chest' },
    { name: 'Pull-Ups',              emoji: '🔝', muscle: 'Back' },
    { name: 'Shoulder Press',        emoji: '🦅', muscle: 'Shoulders' },
    { name: 'Barbell Rows',          emoji: '🚣', muscle: 'Back' },
    { name: 'Dips',                  emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Barbell Curl',          emoji: '🔄', muscle: 'Biceps' },
    { name: 'Power Clean',           emoji: '⚡', muscle: 'Full Body' },
    { name: 'Kettlebell Swings',     emoji: '🔔', muscle: 'Full Body' },
    { name: 'Turkish Get-Up',        emoji: '🌅', muscle: 'Full Body' },
    { name: 'Farmers Carry',         emoji: '🧺', muscle: 'Full Body' },
  ],
  Cardio: [
    { name: 'Treadmill Run',         emoji: '🏃', muscle: 'Cardio' },
    { name: 'Jump Rope',             emoji: '🪢', muscle: 'Cardio' },
    { name: 'Cycling',               emoji: '🚴', muscle: 'Cardio' },
    { name: 'Stair Climber',         emoji: '🪜', muscle: 'Cardio' },
    { name: 'Rowing Machine',        emoji: '🚣', muscle: 'Cardio' },
    { name: 'Elliptical',            emoji: '🔄', muscle: 'Cardio' },
    { name: 'Sprint Intervals',      emoji: '⚡', muscle: 'Cardio' },
    { name: 'Swimming',              emoji: '🏊', muscle: 'Cardio' },
    { name: 'Assault Bike',          emoji: '💨', muscle: 'Cardio' },
    { name: 'Incline Walk',          emoji: '⛰️', muscle: 'Cardio' },
  ],
  HIIT: [
    { name: 'Burpees',               emoji: '💥', muscle: 'Full Body' },
    { name: 'Box Jumps',             emoji: '📦', muscle: 'Legs' },
    { name: 'Mountain Climbers',     emoji: '🧗', muscle: 'Core' },
    { name: 'Jump Squats',           emoji: '⬆️', muscle: 'Legs' },
    { name: 'Kettlebell Swings',     emoji: '🔔', muscle: 'Full Body' },
    { name: 'Battle Ropes',          emoji: '🌊', muscle: 'Arms/Core' },
    { name: 'Jumping Lunges',        emoji: '🦘', muscle: 'Legs' },
    { name: 'High Knees',            emoji: '🦵', muscle: 'Cardio' },
    { name: 'Plyo Push-Ups',         emoji: '💨', muscle: 'Chest' },
    { name: 'Tuck Jumps',            emoji: '🐸', muscle: 'Legs' },
    { name: 'Assault Bike Sprint',   emoji: '🚴', muscle: 'Cardio' },
    { name: 'Sled Push',             emoji: '🛷', muscle: 'Full Body' },
  ],
  Mobility: [
    { name: 'Hip Flexor Stretch',    emoji: '🧘', muscle: 'Hips' },
    { name: 'Shoulder Dislocates',   emoji: '🔄', muscle: 'Shoulders' },
    { name: 'Cat-Cow',               emoji: '🐱', muscle: 'Spine' },
    { name: 'Pigeon Pose',           emoji: '🕊️', muscle: 'Hips/Glutes' },
    { name: 'Worlds Greatest Stretch', emoji: '🌍', muscle: 'Full Body' },
    { name: 'Thoracic Rotation',     emoji: '🌀', muscle: 'Upper Back' },
    { name: 'Deep Squat Hold',       emoji: '🏋️', muscle: 'Hips/Ankles' },
    { name: 'Couch Stretch',         emoji: '🛋️', muscle: 'Hip Flexors' },
    { name: 'Downward Dog',          emoji: '🐕', muscle: 'Full Body' },
    { name: '90/90 Hip Switch',      emoji: '🔁', muscle: 'Hips' },
    { name: 'Wall Slides',           emoji: '🧱', muscle: 'Shoulders' },
    { name: 'Jefferson Curl',        emoji: '🌿', muscle: 'Spine/Hamstrings' },
  ],
  Powerlifting: [
    { name: 'Barbell Back Squat',    emoji: '🏆', muscle: 'Quads/Glutes' },
    { name: 'Conventional Deadlift', emoji: '🏋️', muscle: 'Full Body' },
    { name: 'Bench Press',           emoji: '💪', muscle: 'Chest' },
    { name: 'Sumo Deadlift',         emoji: '🔱', muscle: 'Glutes/Back' },
    { name: 'Close-Grip Bench',      emoji: '🤜', muscle: 'Triceps' },
    { name: 'Pause Squat',           emoji: '⏸️', muscle: 'Quads' },
    { name: 'Rack Pull',             emoji: '🔧', muscle: 'Back' },
    { name: 'Romanian Deadlift',     emoji: '🏗️', muscle: 'Hamstrings' },
    { name: 'Box Squat',             emoji: '📦', muscle: 'Quads/Glutes' },
    { name: 'Floor Press',           emoji: '⬛', muscle: 'Chest/Triceps' },
    { name: 'Good Mornings',         emoji: '🌅', muscle: 'Hamstrings/Back' },
    { name: 'Belt Squat',            emoji: '🎽', muscle: 'Quads' },
  ],
  Calisthenics: [
    { name: 'Pull-Ups',              emoji: '🔝', muscle: 'Back/Biceps' },
    { name: 'Dips',                  emoji: '🤸', muscle: 'Chest/Triceps' },
    { name: 'Push-Ups',              emoji: '⬆️', muscle: 'Chest' },
    { name: 'Muscle-Up',             emoji: '⭐', muscle: 'Full Body' },
    { name: 'Handstand Push-Up',     emoji: '🙃', muscle: 'Shoulders' },
    { name: 'L-Sit',                 emoji: '💺', muscle: 'Core' },
    { name: 'Front Lever',           emoji: '📐', muscle: 'Back/Core' },
    { name: 'Human Flag',            emoji: '🚩', muscle: 'Full Body' },
    { name: 'Pistol Squat',          emoji: '🦯', muscle: 'Quads' },
    { name: 'Dragon Flag',           emoji: '🐉', muscle: 'Core' },
    { name: 'Hollow Body Hold',      emoji: '🫙', muscle: 'Core' },
    { name: 'Ring Rows',             emoji: '💍', muscle: 'Back' },
  ],
  Custom: [],
};
